# Generated by Django 3.2.6 on 2021-08-11 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='stayId',
        ),
    ]
