# Generated by Django 3.2.6 on 2021-08-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owners', '0002_remove_owner_stayid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='description',
        ),
        migrations.AddField(
            model_name='owner',
            name='location',
            field=models.CharField(default=True, max_length=200),
        ),
    ]
