# Generated by Django 3.2.6 on 2021-08-11 09:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('owners', '0004_alter_owner_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zipcode', models.CharField(max_length=20)),
                ('discription', models.TextField(blank=True)),
                ('maxNoPerson', models.IntegerField()),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.DecimalField(decimal_places=1, max_digits=2)),
                ('photoMain', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo6', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('listedDate', models.DateField(blank=True, default=datetime.datetime.now)),
                ('pricePerPerson', models.IntegerField()),
                ('hostWelcome', multiselectfield.db.fields.MultiSelectField(choices=[('Families', 'Families'), ('Couples', 'Couples'), ('Students', 'Students'), ('Males', 'Males'), ('Females', 'Females')], max_length=39)),
                ('amenities', multiselectfield.db.fields.MultiSelectField(choices=[('Free parking', 'Free parking'), ('Children Activities', 'Children Activities'), ('Free Internet', 'Free Internet'), ('Dry cleaning', 'Dry cleaning'), ('TV', 'TV')], max_length=62)),
                ('meals', multiselectfield.db.fields.MultiSelectField(choices=[('Provided', 'Provided'), ('Use Kitchen', 'Use Kitchen')], max_length=20)),
                ('bookingDate', models.DateField(blank=True)),
                ('closingDate', models.DateField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='owners.owner')),
            ],
        ),
    ]
