# Generated by Django 3.2.6 on 2021-08-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0005_auto_20210812_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='avgReview',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='stay',
            name='countReview',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
