# Generated by Django 3.2.6 on 2021-08-17 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0006_auto_20210812_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stay',
            name='avgReview',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=2),
        ),
    ]
