# Generated by Django 3.2.6 on 2021-08-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stayID', models.IntegerField()),
                ('userID', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('rating', models.IntegerField(max_length=1)),
            ],
        ),
    ]
