# Generated by Django 3.2.6 on 2021-08-15 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0006_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stayTitle',
            field=models.TextField(),
        ),
    ]
