# Generated by Django 3.2.6 on 2021-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0007_alter_review_staytitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stayID',
            field=models.IntegerField(default=1),
        ),
    ]
