# Generated by Django 3.2.6 on 2021-08-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0008_review_stayid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='stayID',
            field=models.IntegerField(),
        ),
    ]
