# Generated by Django 3.2.6 on 2021-08-15 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0009_alter_review_stayid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='stayID',
        ),
    ]
