# Generated by Django 3.2.6 on 2021-08-15 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0010_remove_review_stayid'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='stayID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='review',
            name='stayTitle',
            field=models.CharField(max_length=300),
        ),
    ]
