# Generated by Django 3.2.6 on 2021-08-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0012_alter_review_stayid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='userName',
            field=models.CharField(max_length=40),
        ),
    ]
