# Generated by Django 3.2.6 on 2021-08-10 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquires', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enquires',
            new_name='Enquire',
        ),
    ]
