# Generated by Django 3.2.6 on 2021-08-11 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquires', '0002_rename_enquires_enquire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='bookingDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='closingDate',
            field=models.DateField(blank=True),
        ),
    ]
