# Generated by Django 3.2.6 on 2021-08-11 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquires', '0005_auto_20210811_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='bookingDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='closingDate',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='userID',
            field=models.IntegerField(),
        ),
    ]
