# Generated by Django 3.2.6 on 2021-08-11 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_auto_20210811_1508'),
        ('enquires', '0006_auto_20210811_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stays.stay'),
        ),
    ]
