# Generated by Django 3.2.6 on 2021-08-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stays', '0002_auto_20210811_1508'),
        ('enquires', '0007_alter_enquire_stay'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquire',
            name='userID',
        ),
        migrations.AddField(
            model_name='enquire',
            name='userName',
            field=models.CharField(default=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='stay',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='stays.stay'),
        ),
    ]
