# Generated by Django 3.2.6 on 2021-08-11 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquires', '0009_auto_20210811_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enquire',
            old_name='stay',
            new_name='stayTitle',
        ),
    ]
