# Generated by Django 3.2.6 on 2021-08-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquires', '0011_alter_enquire_staytitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquire',
            name='stayId',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enquire',
            name='userId',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='stayTitle',
            field=models.CharField(max_length=200),
        ),
    ]
