# Generated by Django 3.2.6 on 2021-08-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquires', '0012_auto_20210815_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquire',
            name='stayId',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='enquire',
            name='userId',
            field=models.IntegerField(blank=True),
        ),
    ]
